CREATE TABLE IF NOT EXISTS "在职花名册表" (
    "人员编号" TEXT PRIMARY KEY,
    "查询日期" DATE NOT NULL,
    "序号" TEXT,
    "公司" TEXT,
    "公司ID" TEXT,
    "部门" TEXT,
    "部门长文本" TEXT,
    "部门ID" TEXT,
    "部门所属城市" TEXT,
    "姓名" TEXT,
    "职位编码" TEXT,
    "职位名称" TEXT,
    "具体岗位_新" TEXT,
    "是否关键岗位" TEXT,
    "岗位族" TEXT,
    "职务" TEXT,
    "一级职能名称" TEXT,
    "二级职能名称" TEXT,
    "标准岗位编码" TEXT,
    "标准岗位名称" TEXT,
    "上级编码" TEXT,
    "上级名称" TEXT,
    "对接HR工号" TEXT,
    "对接HR姓名" TEXT,
    "班长" TEXT,
    "员工组" TEXT,
    "员工子组" TEXT,
    "子标签" TEXT,
    "入职日期" DATE,
    "司龄" TEXT,
    "性别" TEXT,
    "出生日期" DATE,
    "生日类型" TEXT,
    "实际生日" TEXT,
    "年龄" TEXT,
    "户口所在省" TEXT,
    "户口所在市" TEXT,
    "户籍地" TEXT,
    "参保地" TEXT,
    "婚姻状况" TEXT,
    "学历" TEXT,
    "学习形式" TEXT,
    "毕业时间" DATE,
    "学位" TEXT,
    "学校" TEXT,
    "其他院校" TEXT,
    "院校专业" TEXT,
    "证件号码" TEXT,
    "联系电话" TEXT,
    "万科邮箱" TEXT,
    "万物云邮箱" TEXT,
    "域账号" TEXT,
    "雇佣状态" TEXT,
    "部门分类" TEXT,
    "部门子分类" TEXT,
    "是否外盘人员" TEXT,
    "合同类型" TEXT,
    "合同签订主体" TEXT,
    "合同开始日期" DATE,
    "合同结束日期" DATE,
    "参加工作时间" DATE,
    "服务万科时间" DATE,
    "最新入职万科日期" DATE,
    "司龄起算时间" DATE,
    "工龄" TEXT,
    "储备见习类型" TEXT,
    "储备见习开始日期" DATE,
    "储备见习结束日期" DATE,
    "储备岗位名称" TEXT,
    "岗位备注_物业" TEXT,
    "序列属性" TEXT,
    "序列类型" TEXT,
    "组织路径ID" TEXT,
    "组织路径名称" TEXT,
    "合同期限" TEXT,
    "是否服过兵役" TEXT,
    "退役证编号" TEXT,
    "退伍证类型" TEXT,
    "入伍时间" DATE,
    "退役时间" DATE,
    "领导力类别" TEXT,
    "证件是否永久有效" TEXT,
    "证件有效期起" DATE,
    "证件有效期止" DATE,
    "是否主任职" TEXT,
    "任职类型" TEXT,
    "民族" TEXT,
    "户口性质" TEXT,
    "户口所在地" TEXT,
    "出生地" TEXT,
    "籍贯" TEXT,
    "国籍" TEXT,
    "出生国家" TEXT,
    "出生地所在省" TEXT,
    "出生地所在市" TEXT,
    "校招届别" TEXT,
    "政治面貌" TEXT,
    "所属党组织全称" TEXT,
    "党员状态" TEXT,
    "来源文件名" TEXT NOT NULL,
    "导入批次号" TEXT NOT NULL,
    "导入行号" INTEGER,
    "下载时间" TIMESTAMP NULL,
    "导入时间" TIMESTAMP NOT NULL DEFAULT NOW(),
    "扩展字段JSON" JSONB NULL,
    "记录创建时间" TIMESTAMP NOT NULL DEFAULT NOW(),
    "记录更新时间" TIMESTAMP NOT NULL DEFAULT NOW()
);
