CREATE TABLE IF NOT EXISTS "组织列表" (
    org_code TEXT PRIMARY KEY,
    row_no INTEGER,
    org_name TEXT,
    org_type TEXT,
    parent_org_name TEXT,
    parent_org_code TEXT,
    established_date TEXT,
    company_name TEXT,
    business_status TEXT,
    org_level TEXT,
    org_function TEXT,
    city_name TEXT,
    work_location TEXT,
    physical_level TEXT,
    pending_disable_date TEXT,
    department_type TEXT,
    process_level_name TEXT,
    dept_subcategory_code TEXT,
    dept_subcategory_name TEXT,
    dept_category_code TEXT,
    dept_category_name TEXT,
    org_created_time TEXT,
    org_full_name TEXT,
    org_manager_name TEXT,
    hr_owner_employee_no TEXT,
    hr_owner_name TEXT,
    hr_owner_include_children_flag TEXT,
    hr_owner_exposed_flag TEXT,
    source_root_org TEXT,
    include_all_children BOOLEAN NOT NULL DEFAULT TRUE,
    source_file_name TEXT,
    import_batch_no TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_组织列表_parent_org_code ON "组织列表" (parent_org_code);
CREATE INDEX IF NOT EXISTS idx_组织列表_import_batch_no ON "组织列表" (import_batch_no);
