CREATE TABLE IF NOT EXISTS "组织列表" (
    "行政组织编码" TEXT PRIMARY KEY,
    "序号" INTEGER,
    "行政组织名称" TEXT,
    "行政组织类型" TEXT,
    "上级行政组织" TEXT,
    "上级行政组织编码" TEXT,
    "成立日期" TEXT,
    "所属公司" TEXT,
    "业务状态" TEXT,
    "行政组织层级" TEXT,
    "行政组织职能" TEXT,
    "所在城市" TEXT,
    "工作地" TEXT,
    "物理层级" TEXT,
    "待停用日期" TEXT,
    "部门类型" TEXT,
    "流程层级_名称" TEXT,
    "部门子分类_编码" TEXT,
    "部门子分类_名称" TEXT,
    "部门分类_编码" TEXT,
    "部门分类_名称" TEXT,
    "创建时间" TEXT,
    "组织长名称" TEXT,
    "组织负责人" TEXT,
    "责任HR工号" TEXT,
    "责任HR姓名" TEXT,
    "责任HR含下级组织" TEXT,
    "责任HR是否透出" TEXT,
    "来源根组织" TEXT,
    "包含所有下级" BOOLEAN NOT NULL DEFAULT TRUE,
    "来源文件名" TEXT,
    "导入批次号" TEXT,
    "记录创建时间" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "记录更新时间" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_组织列表_parent_org_code ON "组织列表" ("上级行政组织编码");
CREATE INDEX IF NOT EXISTS idx_组织列表_import_batch_no ON "组织列表" ("导入批次号");
