CREATE TABLE IF NOT EXISTS "人员属性查询" (
    "工号" VARCHAR(64) PRIMARY KEY,
    "姓名" VARCHAR(128),
    "部门ID" VARCHAR(64),
    "组织单位" VARCHAR(128),
    "员工组" VARCHAR(64),
    "员工子组" VARCHAR(64),
    "一级职能名称" VARCHAR(128),
    "二级职能名称" VARCHAR(128),
    "职位名称" VARCHAR(128),
    "标准岗位名称" VARCHAR(128),
    "组织路径名称" TEXT,
    "万御城市营业部" VARCHAR(128),
    "责任HR工号" VARCHAR(64),
    "责任HR导入批次号" VARCHAR(64),
    "花名册查询日期" DATE,
    "花名册导入批次号" VARCHAR(64),
    "花名册匹配状态" VARCHAR(32),
    "申请人HR类型" VARCHAR(8),
    "是否责任HR" BOOLEAN NOT NULL DEFAULT FALSE,
    "是否HR人员" BOOLEAN NOT NULL DEFAULT FALSE,
    "是否疑似HR人员" BOOLEAN NOT NULL DEFAULT FALSE,
    "HR主判定依据" VARCHAR(128),
    "HR主判定值" TEXT,
    "HR子域" VARCHAR(64),
    "HR判定原因" VARCHAR(128),
    "记录创建时间" TIMESTAMP NOT NULL DEFAULT NOW(),
    "记录更新时间" TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE "人员属性查询"
ADD COLUMN IF NOT EXISTS "工号" VARCHAR(64),
ADD COLUMN IF NOT EXISTS "姓名" VARCHAR(128),
ADD COLUMN IF NOT EXISTS "部门ID" VARCHAR(64),
ADD COLUMN IF NOT EXISTS "组织单位" VARCHAR(128),
ADD COLUMN IF NOT EXISTS "员工组" VARCHAR(64),
ADD COLUMN IF NOT EXISTS "员工子组" VARCHAR(64),
ADD COLUMN IF NOT EXISTS "一级职能名称" VARCHAR(128),
ADD COLUMN IF NOT EXISTS "二级职能名称" VARCHAR(128),
ADD COLUMN IF NOT EXISTS "职位名称" VARCHAR(128),
ADD COLUMN IF NOT EXISTS "标准岗位名称" VARCHAR(128),
ADD COLUMN IF NOT EXISTS "组织路径名称" TEXT,
ADD COLUMN IF NOT EXISTS "万御城市营业部" VARCHAR(128),
ADD COLUMN IF NOT EXISTS "责任HR工号" VARCHAR(64),
ADD COLUMN IF NOT EXISTS "责任HR导入批次号" VARCHAR(64),
ADD COLUMN IF NOT EXISTS "花名册查询日期" DATE,
ADD COLUMN IF NOT EXISTS "花名册导入批次号" VARCHAR(64),
ADD COLUMN IF NOT EXISTS "花名册匹配状态" VARCHAR(32),
ADD COLUMN IF NOT EXISTS "申请人HR类型" VARCHAR(8),
ADD COLUMN IF NOT EXISTS "是否责任HR" BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS "是否HR人员" BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS "是否疑似HR人员" BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS "HR主判定依据" VARCHAR(128),
ADD COLUMN IF NOT EXISTS "HR主判定值" TEXT,
ADD COLUMN IF NOT EXISTS "HR子域" VARCHAR(64),
ADD COLUMN IF NOT EXISTS "HR判定原因" VARCHAR(128),
ADD COLUMN IF NOT EXISTS "记录创建时间" TIMESTAMP NOT NULL DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS "记录更新时间" TIMESTAMP NOT NULL DEFAULT NOW();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = '"人员属性查询"'::regclass
          AND contype = 'p'
    ) THEN
        ALTER TABLE "人员属性查询"
        ADD CONSTRAINT "人员属性查询_pkey" PRIMARY KEY ("工号");
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_person_attributes_hr_type
ON "人员属性查询"("申请人HR类型");

CREATE INDEX IF NOT EXISTS idx_person_attributes_department_id
ON "人员属性查询"("部门ID");

CREATE INDEX IF NOT EXISTS idx_person_attributes_responsible_hr
ON "人员属性查询"("是否责任HR");
