CREATE TABLE IF NOT EXISTS "人员档案修改审核单基本信息" (
    "单据编号" VARCHAR(64) PRIMARY KEY,
    "单据名称" TEXT,
    "单据状态" VARCHAR(64),
    "提交时间" VARCHAR(64),
    "创建人姓名" VARCHAR(128),
    "创建人工号" VARCHAR(64),
    "变更人" VARCHAR(128),
    "提交变更时间" VARCHAR(64),
    "申请人摘要信息" TEXT,
    "区段数量" INTEGER,
    "附件数量" INTEGER,
    "原始快照" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "记录创建时间" TIMESTAMP NOT NULL DEFAULT NOW(),
    "记录更新时间" TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE "人员档案修改审核单基本信息"
ADD COLUMN IF NOT EXISTS "单据名称" TEXT,
ADD COLUMN IF NOT EXISTS "单据状态" VARCHAR(64),
ADD COLUMN IF NOT EXISTS "提交时间" VARCHAR(64),
ADD COLUMN IF NOT EXISTS "创建人姓名" VARCHAR(128),
ADD COLUMN IF NOT EXISTS "创建人工号" VARCHAR(64),
ADD COLUMN IF NOT EXISTS "变更人" VARCHAR(128),
ADD COLUMN IF NOT EXISTS "提交变更时间" VARCHAR(64),
ADD COLUMN IF NOT EXISTS "申请人摘要信息" TEXT,
ADD COLUMN IF NOT EXISTS "区段数量" INTEGER,
ADD COLUMN IF NOT EXISTS "附件数量" INTEGER,
ADD COLUMN IF NOT EXISTS "原始快照" JSONB NOT NULL DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS "记录创建时间" TIMESTAMP NOT NULL DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS "记录更新时间" TIMESTAMP NOT NULL DEFAULT NOW();

CREATE TABLE IF NOT EXISTS "人员档案修改审核单区段字段" (
    "区段字段ID" BIGSERIAL PRIMARY KEY,
    "单据编号" VARCHAR(64) NOT NULL,
    "区段序号" INTEGER,
    "区段名称" VARCHAR(128),
    "子区段序号" INTEGER,
    "子区段名称" VARCHAR(128),
    "表头快照" JSONB NOT NULL DEFAULT '[]'::jsonb,
    "行序号" INTEGER,
    "字段序号" INTEGER,
    "字段名称" VARCHAR(128),
    "字段值" TEXT,
    "字段类型" VARCHAR(64),
    "原始快照" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "记录创建时间" TIMESTAMP NOT NULL DEFAULT NOW(),
    "记录更新时间" TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE "人员档案修改审核单区段字段"
ADD COLUMN IF NOT EXISTS "单据编号" VARCHAR(64),
ADD COLUMN IF NOT EXISTS "区段序号" INTEGER,
ADD COLUMN IF NOT EXISTS "区段名称" VARCHAR(128),
ADD COLUMN IF NOT EXISTS "子区段序号" INTEGER,
ADD COLUMN IF NOT EXISTS "子区段名称" VARCHAR(128),
ADD COLUMN IF NOT EXISTS "表头快照" JSONB NOT NULL DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS "行序号" INTEGER,
ADD COLUMN IF NOT EXISTS "字段序号" INTEGER,
ADD COLUMN IF NOT EXISTS "字段名称" VARCHAR(128),
ADD COLUMN IF NOT EXISTS "字段值" TEXT,
ADD COLUMN IF NOT EXISTS "字段类型" VARCHAR(64),
ADD COLUMN IF NOT EXISTS "原始快照" JSONB NOT NULL DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS "记录创建时间" TIMESTAMP NOT NULL DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS "记录更新时间" TIMESTAMP NOT NULL DEFAULT NOW();

CREATE TABLE IF NOT EXISTS "人员档案修改审核单附件" (
    "附件ID" BIGSERIAL PRIMARY KEY,
    "单据编号" VARCHAR(64) NOT NULL,
    "区段序号" INTEGER,
    "区段名称" VARCHAR(128),
    "子区段序号" INTEGER,
    "子区段名称" VARCHAR(128),
    "行序号" INTEGER,
    "变更项" VARCHAR(256),
    "附件序号" INTEGER,
    "附件名称" TEXT,
    "附件原值" TEXT,
    "附件新值" TEXT,
    "相对路径" TEXT,
    "下载状态" VARCHAR(64),
    "下载时间" TIMESTAMP,
    "文件大小" BIGINT,
    "文件哈希" VARCHAR(128),
    "数据引用ID" VARCHAR(128),
    "原始快照" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "记录创建时间" TIMESTAMP NOT NULL DEFAULT NOW(),
    "记录更新时间" TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE "人员档案修改审核单附件"
ADD COLUMN IF NOT EXISTS "单据编号" VARCHAR(64),
ADD COLUMN IF NOT EXISTS "区段序号" INTEGER,
ADD COLUMN IF NOT EXISTS "区段名称" VARCHAR(128),
ADD COLUMN IF NOT EXISTS "子区段序号" INTEGER,
ADD COLUMN IF NOT EXISTS "子区段名称" VARCHAR(128),
ADD COLUMN IF NOT EXISTS "行序号" INTEGER,
ADD COLUMN IF NOT EXISTS "变更项" VARCHAR(256),
ADD COLUMN IF NOT EXISTS "附件序号" INTEGER,
ADD COLUMN IF NOT EXISTS "附件名称" TEXT,
ADD COLUMN IF NOT EXISTS "附件原值" TEXT,
ADD COLUMN IF NOT EXISTS "附件新值" TEXT,
ADD COLUMN IF NOT EXISTS "相对路径" TEXT,
ADD COLUMN IF NOT EXISTS "下载状态" VARCHAR(64),
ADD COLUMN IF NOT EXISTS "下载时间" TIMESTAMP,
ADD COLUMN IF NOT EXISTS "文件大小" BIGINT,
ADD COLUMN IF NOT EXISTS "文件哈希" VARCHAR(128),
ADD COLUMN IF NOT EXISTS "数据引用ID" VARCHAR(128),
ADD COLUMN IF NOT EXISTS "原始快照" JSONB NOT NULL DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS "记录创建时间" TIMESTAMP NOT NULL DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS "记录更新时间" TIMESTAMP NOT NULL DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_profile_change_audit_basic_status
ON "人员档案修改审核单基本信息" ("单据状态");

CREATE INDEX IF NOT EXISTS idx_profile_change_audit_basic_submit_time
ON "人员档案修改审核单基本信息" ("提交时间");

CREATE INDEX IF NOT EXISTS idx_profile_change_audit_section_document
ON "人员档案修改审核单区段字段" ("单据编号", "区段序号", "子区段序号", "行序号", "字段序号");

CREATE INDEX IF NOT EXISTS idx_profile_change_audit_attachment_document
ON "人员档案修改审核单附件" ("单据编号", "区段序号", "子区段序号", "行序号", "附件序号");
